### ISSUE TITLE
Cannot run Pegasus demo

### ISSUE THREAD

**Issue by OkySabeni** [vimeo/Pegasus#3]
First, I had to fix the Podfile file by changing 

installer_representation.project.targets.each do |target| to 
installer_representation.pods_project.targets.each do |target| for the latest version of cocoapods.

After installing the pods, when I try to build the project, I get the [UIApplication sharedApplication] is unavailable in keyboard extension error. There is a lengthy discussion on https://github.com/AFNetworking/AFNetworking/issues/2119

I tried all the solutions but it still does not work for me.

**Comment by georgel** [comment]
Ditto

**Comment by Muesly** [comment]
That part of the script didn't seem to add what it was supposed to so I went into AFNetworking build settings and manually added AF_APP_EXTENSIONS=1 to Preprocessor Definitions

**Comment by alfiehanssen** [comment]
We're working on a new upload library that is slated to be released later this year. It will contain a robust sample project. In the meantime, please refer to the README files for the VIMNetworking and VIMUpload projects for the most up to date documentation. Pegasus will likely not be upgraded or supported going forward, and will eventually be deprecated.
